### ISSUE TITLE
Deprecated selector in `rain-syntax\index.less`

### ISSUE THREAD

**Issue by Bluorenge** [pfist/rain-syntax#3]
In `rain-syntax\index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor,
:host` => `atom-text-editor,atom-text-editor`

* `atom-text-editor .line.cursor-line,
:host .line.cursor-line` => `atom-text-editor .line.cursor-line,atom-text-editor .line.cursor-line`

* `atom-text-editor .invisible,
:host .invisible` => `atom-text-editor .invisible,atom-text-editor .invisible`

* `atom-text-editor .cursor,
:host .cursor` => `atom-text-editor .cursor,atom-text-editor .cursor`

* `atom-text-editor .selection .region,
:host .selection .region` => `atom-text-editor .selection .region,atom-text-editor .selection .region`

* `atom-text-editor .bracket-matcher .region,
:host .bracket-matcher .region` => `atom-text-editor .bracket-matcher .region,atom-text-editor .bracket-matcher .region`

* `atom-text-editor .invisible-character,
:host .invisible-character` => `atom-text-editor .invisible-character,atom-text-editor .invisible-character`

* `atom-text-editor .indent-guide,
:host .indent-guide` => `atom-text-editor .indent-guide,atom-text-editor .indent-guide`

* `atom-text-editor .wrap-guide,
:host .wrap-guide` => `atom-text-editor .wrap-guide,atom-text-editor .wrap-guide`

* `atom-text-editor .find-result .region.region.region,
:host .find-result .region.region.region,
atom-text-editor .current-result .region.region.region,
:host .current-result .region.region.region` => `atom-text-editor .find-result .region.region.region,atom-text-editor .find-result .region.region.region,
atom-text-editor .current-result .region.region.region,atom-text-editor .current-result .region.region.region`

* `atom-text-editor .find-result .region.region.region,
:host .find-result .region.region.region` => `atom-text-editor .find-result .region.region.region,atom-text-editor .find-result .region.region.region`

* `atom-text-editor .current-result .region.region.region,
:host .current-result .region.region.region` => `atom-text-editor .current-result .region.region.region,atom-text-editor .current-result .region.region.region`

* `atom-text-editor .gutter .line-number,
:host .gutter .line-number` => `atom-text-editor .gutter .line-number,atom-text-editor .gutter .line-number`

* `atom-text-editor .gutter .line-number.cursor-line,
:host .gutter .line-number.cursor-line` => `atom-text-editor .gutter .line-number.cursor-line,atom-text-editor .gutter .line-number.cursor-line`

* `atom-text-editor .gutter .line-number.cursor-line-no-selection,
:host .gutter .line-number.cursor-line-no-selection` => `atom-text-editor .gutter .line-number.cursor-line-no-selection,atom-text-editor .gutter .line-number.cursor-line-no-selection`

* `atom-text-editor .gutter .line-number .icon-right,
:host .gutter .line-number .icon-right` => `atom-text-editor .gutter .line-number .icon-right,atom-text-editor .gutter .line-number .icon-right`

* `atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before,
:host .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before` => `atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before,atom-text-editor .gutter:not(.git-diff-icon) .line-number.git-line-removed.git-line-removed::before`

* `atom-text-editor .gutter:not(

**Comment by TechMaz** [comment]
bump

**Comment by rcrooks** [comment]
@polymoon since I love this theme but was tired of the deprecation notices too -- so I forked and fixed the selectors. However, for some reason I can not push my changes back to the fork to open a PR, so instead just attaching my edited files here.
[styles.zip](https://github.com/polymoon/rain-syntax/files/1352541/styles.zip)

**Comment by pfist** [comment]
This was finally fixed in the 2.1.0 release. Thanks!

**Comment by rcrooks** [comment]
awesome, thanks @polymoon
